# Generated by Django 4.1.6 on 2023-02-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='hggh', upload_to='pictures'),
            preserve_default=False,
        ),
    ]
